version: 4
  
shared:
    image: node:12

cache:
  job:
    component-bf1:
      - $SD_SOURCE_DIR/1g.bin

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  invalid-image-bf1:
    annotations: 
      screwdriver.cd/buildCluster: bf1
    image: invalid_node_image
    steps:
      - build: echo "build"
  component-default-working:
    annotations: 
      screwdriver.cd/cpu: 16
      screwdriver.cd/ram: 20
    steps:
      - build: echo "build"
      - sl: sleep 10m
  component-gq1:
    annotations: 
      screwdriver.cd/buildCluster: gq1
      screwdriver.cd/cpu: 16
      screwdriver.cd/ram: 20      
    steps:
      - build: echo "build"
      - exp: export
      - sl: sleep 10m
  component-bf1:
    image: centos:centos7
    annotations: 
      screwdriver.cd/buildCluster: bf1
    steps:
      - build: echo "build"   
      - dd: dd if=/dev/zero of=1g.bin bs=1G count=1 || true
      - dd1: dd if=/dev/urandom of=tmpfile bs=10240 count=100000
      - ex: export
  trigger-beta:
      image: centos:centos7
      environment:
          PIPELINE_ID: 8187
          INSTANCE: "https://beta.api.screwdriver.cd"
          NAMESPACE: v4
          TIMEOUT: 10
      steps:
        - install_jq: yum install epel-release -y && yum update -y && yum install jq -y && jq -Version
        - trigger_beta_functiona_test: |
            TOKEN=$(curl -m ${TIMEOUT} --fail ${INSTANCE}/${NAMESPACE}/auth/token?api_token=${ACCESS_TOKEN} | jq -r '.token')
            echo "$TOKEN"
            [[ -z "$TOKEN" ]] && echo "empty Token" && exit 1
            JOB_ID=$(curl -m ${TIMEOUT} --fail -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" ${INSTANCE}/${NAMESPACE}/pipelines/${PIPELINE_ID}/jobs | jq -r '.[0].id')
            echo "$JOB_ID"
            [[ -z "$JOB_ID" ]] && echo "empty Job Id" && exit 1
            BUILD_ID=$(curl -m ${TIMEOUT} --fail -d "jobId=${JOB_ID}" -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer ${TOKEN}" -X POST ${INSTANCE}/${NAMESPACE}/builds | jq -r '.id')
            echo "$BUILD_ID"
            [[ -z "$BUILD_ID" ]] && echo "empty Build Id" && exit 1
            for attempts in {1..2}; do
              STATUS=$(curl -m ${TIMEOUT} --fail -H "Authorization: Bearer ${TOKEN}" ${INSTANCE}/${NAMESPACE}/builds/${BUILD_ID} | jq -r '.status')
              echo "Build ${BUILD_ID} started, polling status..."              
              if [ "${STATUS}" = "SUCCESS" ]; then 
                echo "Build ${BUILD_ID} ${STATUS}"
                break
              fi

              if [ "${STATUS}" = "FAILURE" ] || [ "${STATUS}" = "ABORTED" ]; then
                echo "Build ${BUILD_ID} ${STATUS}"
                break
              fi

              if [ "${STATUS}" = "RUNNING" ] || [ "${STATUS}" = "QUEUED" ]; then
                echo "Build ${BUILD_ID} ${STATUS}, wait 30s..."
                sleep 2s
              fi
            done
            if [ "${STATUS}" -ne "SUCCESS" ]; then
              echo "Build ${BUILD_ID} monitoring timed out"
              exit 1
            fi                
      secrets:
        - ACCESS_TOKEN
