shared:
  image: node:12 
  annotations:
    screwdriver.cd/timeout: 1

jobs:
  testabort:
    image: node:12
    steps:
      - env: export FACTORY_BUILD_STATUS=success
      - sleep: |
          export ABORT_BUILD_STATUS=aborted
          while true; do sleep 1; echo "sleep"; done          
      - teardown-first: |
          export ABORT_BUILD_STATUS_TEARDOWN=aborted-teardown
          export
      - teardown-env: |
          echo $FACTORY_BUILD_STATUS
          echo $ABORT_BUILD_STATUS
          echo $ABORT_BUILD_STATUS_TEARDOWN          
