version: 4
  
shared:
    image: node:12

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component-default:
    steps:
      - build: echo "build"
  component-gq1:
    annotations: 
      screwdriver.cd/buildCluster: gq1
    steps:
      - build: echo "build"
  component-bf1:
    annotations: 
      screwdriver.cd/buildCluster: bf1
    steps:
      - build: echo "build"   
