version: 4

shared:
    image: node:6

jobs:
    main:
        environment:
            SD_ZIP_ARTIFACTS: true
        steps:
            - echo: echo "foo"
        requires: [~pr,~commit]
    main2:
        environment:
            SD_ZIP_ARTIFACTS: false
        steps:
            - echo: echo "foo"
        requires: [~pr,~commit]
    main3:
        steps:
            - echo: echo "foo"
        requires: [~pr,~commit]
