version: 4

annotations: 
    screwdriver.cd/prChain: 12
    
shared:
    image: node:6

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    requires: [~commit]
    steps:
      - build: echo "build"
