version: 4
   
shared:
    image: node:12

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    steps:
      - build: echo "build"
  component1:
    steps:
      - build: echo "build"
  component2:
    steps:
      - build: echo "build"
  component3:
    steps:
      - build: echo "build"
   
