version: 4
   
shared:
  image: node:12
    
annotations:
  screwdriver.cd/ram: 4
  screwdriver.cd/executor: k8s-vm

cache:
  job:
    component-hyper:
      - $SD_SOURCE_DIR/1g.bin
    component-kata:
      - $SD_SOURCE_DIR/1g.bin

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component-hyper:
    annotations:
      screwdriver.cd/ram: 4
      screwdriver.cd/executor: k8s-vm
    steps:
      - build: echo "build"
      - ls: ls -lrt $SD_SOURCE_DIR/1g.bin || true
      - dd: dd if=/dev/zero of=1g.bin bs=1G count=1 || true
      - ex: export
  component-kata:
    annotations:
      screwdriver.cd/ram: 4
      screwdriver.cd/executor: k8s
    steps:
      - build: echo "build"
      - ls: ls -lrt $SD_SOURCE_DIR/1g.bin || true
      - dd: dd if=/dev/zero of=1g.bin bs=1G count=1 || true
      - ex: export
  component2:
    steps:
      - build: echo "build"
  component3:
    steps:
      - build: echo "build"
   
