version: 4

annotations: 
    screwdriver.cd/prChain: 12
    screwdriver.cd/buildCluster: bf1
    screwdriver.cd/executor: k8s
    
shared:
    image: node:12

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    requires: [~commit]
    steps:
      - build: echo "build"
  component1:
    requires: [~commit]
    steps:
      - build: echo "build"
  component2:
    requires: [~commit]
    steps:
      - build: echo "build"
   
