version: 4
  
shared:
    image: node:12

jobs:
  component-beta:
    requires: 
      - ~commit
    steps:
      - slp: export ABORT_BUILD_STATUS=aborted; sleep 2m
      - build: echo "build"
      - teardown-first: export
      
